---
abstract: 'Create and manipulate volume widgets.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.08
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Curses-UI-Volume
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Curses::UI: 0
  Encode: 0
  Readonly: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Curses-UI-Volume
  homepage: https://github.com/tupinek/Curses-UI-Volume
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Curses-UI-Volume
version: 0.01
